<a href="https://colab.research.google.com/github/IlyasNasirov/notebook/blob/main/8_26_NumPy_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [2]:
nums = list([1,2,3,4,5])
arrays = np.array(nums)
arrays

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz oʻlchovli massiv yarating.



`💡Ishora` np.zeros

In [4]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [26]:
arrays = np.arange(9).reshape(3,3)
print(arrays.size)
print(arrays.itemsize)

9
8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [29]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [32]:
arrays = np.zeros(12)
arrays[6]=1
arrays

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [34]:
np.arange(20,60)


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [37]:
arrays = np.arange(20)
arrays[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [38]:
np.arange(12,21).reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [44]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [48]:
np.random.random(8).reshape(2,2,2)

array([[[0.24742709, 0.3731261 ],
        [0.12428266, 0.70644527]],

       [[0.10897406, 0.3470395 ],
        [0.93965676, 0.67078562]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [57]:
arr = np.random.rand(81).reshape(9,9)
print(arr)
print('max:',arr.max())
print('min:',arr.min())

[[0.99488459 0.90347946 0.94309731 0.67590544 0.40529328 0.38798243
  0.65749403 0.27032303 0.24420932]
 [0.07437608 0.05952831 0.18873268 0.35623985 0.50554571 0.07752369
  0.20941287 0.3865396  0.77947244]
 [0.55476074 0.33359058 0.52663907 0.12651156 0.91335935 0.92056546
  0.44341606 0.98366918 0.36588503]
 [0.77636154 0.83272734 0.81595017 0.01643062 0.34782438 0.97167311
  0.32034163 0.11532941 0.52832284]
 [0.3251662  0.11765777 0.03740593 0.3480788  0.47977131 0.26475856
  0.34332596 0.63651956 0.36765288]
 [0.23850678 0.12629571 0.39784202 0.95738539 0.92349247 0.32593906
  0.97532442 0.85551886 0.22406392]
 [0.57430398 0.1649329  0.36611781 0.87069698 0.24324203 0.80635396
  0.51514589 0.0745847  0.59298845]
 [0.92859018 0.92967644 0.90833981 0.76120761 0.9523803  0.3206969
  0.0245519  0.44271369 0.56882461]
 [0.82127395 0.59903284 0.85899296 0.51649553 0.36947936 0.64660615
  0.59844671 0.98767266 0.52230517]]
max: 0.9948845934851522
min: 0.01643062344975088


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
'''
NaN
False
False
NaN
True
False
'''

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [66]:
arr1 = np.random.random(18).reshape(6,3)
arr2 = np.random.random(12).reshape(3,4)
print(arr1)
print()
print(arr2)
print()
arr1.dot(arr2)

[[0.91518642 0.17708886 0.53597117]
 [0.53887883 0.47608984 0.2060656 ]
 [0.2565677  0.32266334 0.31907829]
 [0.49358157 0.5890711  0.54760844]
 [0.67191046 0.17520991 0.03078071]
 [0.80458611 0.65755644 0.02198338]]

[[0.1545225  0.2665076  0.36916933 0.78526347]
 [0.00503912 0.20541083 0.52187456 0.7806333 ]
 [0.03460035 0.73941725 0.64734039 0.08636527]]



array([[0.16085405, 0.67658643, 0.77723271, 0.90319323],
       [0.09279792, 0.39377777, 0.5807913 , 0.81261035],
       [0.05231164, 0.37058777, 0.46965897, 0.48091227],
       [0.0981853 , 0.65745594, 0.84412545, 0.89473444],
       [0.10577321, 0.23781904, 0.35941192, 0.66705981],
       [0.1284008 , 0.36575241, 0.65442122, 1.14702114]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [67]:
'''
9
10
'''

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [74]:
a = np.array([1,2])
b = np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [78]:
'''
RuntimeWarning: invalid value encountered in divide
RuntimeWarning: divide by zero encountered in floor_divide
RuntimeWarning: invalid value encountered in cast
'''

'\nRuntimeWarning: invalid value encountered in divide\nRuntimeWarning: divide by zero encountered in floor_divide\nRuntimeWarning: invalid value encountered in cast\n'

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [79]:
arr1 = np.array([1,2,4,7,3])
arr2 = np.array([3,9,1,0,2,4])
np.intersect1d(arr1,arr2)

array([1, 2, 3, 4])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [93]:
arr = np.random.uniform(low=0,high=10,size=10)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[9.02945939 3.18216266 1.47120032 7.27851047 0.23183325 0.1589604
 0.52739325 0.78916397 2.84464172 1.04865437]
[9. 3. 1. 7. 0. 0. 0. 0. 2. 1.]
[9. 3. 1. 7. 0. 0. 0. 0. 2. 1.]
[9 3 1 7 0 0 0 0 2 1]
[9. 3. 1. 7. 0. 0. 0. 0. 2. 1.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [98]:
np.repeat(np.arange(3),3).reshape(3,3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

arr 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [102]:
arr = np.random.rand(10)
print(arr)
print(np.sort(arr))

[0.7482894  0.24697328 0.85883104 0.07927077 0.56018951 0.24168694
 0.20619753 0.06693215 0.46482514 0.72279677]
[0.06693215 0.07927077 0.20619753 0.24168694 0.24697328 0.46482514
 0.56018951 0.72279677 0.7482894  0.85883104]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [106]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(np.allclose(arr1,arr2))
print(np.array_equal(arr1,arr2))

False
False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [109]:
arr1 = np.arange(18).reshape(6,3)
arr2 = np.arange(12).reshape(3,4)
np.dot(arr1,arr2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [119]:
arr = np.random.rand(5)
print(arr)
arr[arr.argmax()]=0
arr

[0.07131775 0.36459741 0.55325627 0.20599751 0.29529116]


array([0.07131775, 0.36459741, 0.        , 0.20599751, 0.29529116])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [128]:
today=np.datetime64('today')
yesterday=today-np.timedelta64(1,'D')
tomorrow=today+np.timedelta64(1,'D')
print(today)
print(yesterday)
print(tomorrow)

2025-07-23
2025-07-22
2025-07-24


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [136]:
dates = np.arange('2016-01-01','2016-02-01',dtype='datetime64[D]')
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [141]:
arr = np.random.uniform(low=-10,high=0,size=10)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[-8.17235426 -2.2610478  -8.18417003 -7.84746959 -8.93899048 -7.65959122
 -5.83319019 -0.02260185 -6.88048167 -4.09367438]
[-9. -3. -9. -8. -9. -8. -6. -1. -7. -5.]
[-9. -3. -9. -8. -9. -8. -6. -1. -7. -5.]
[-8 -2 -8 -7 -8 -7 -5  0 -6 -4]
[-8. -2. -8. -7. -8. -7. -5. -0. -6. -4.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [144]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
result = np.add.reduce([a,b,c])
result

array([12, 15, 18])

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [154]:
arr = np.array([1,2,3,4,5])
result = np.zeros(len(arr) * 4 - 3, dtype=int)
result[::4] = arr
result

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`