<a href="https://colab.research.google.com/github/IlyasNasirov/notebook/blob/main/8_26_NumPy_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [3]:
nums = list([1,2,3,4,5])
arrays = np.array(nums)
arrays

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz oʻlchovli massiv yarating.



`💡Ishora` np.zeros

In [4]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
arrays = np.arange(9).reshape(3,3)
print(arrays.size)
print(arrays.itemsize)

9
8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [7]:
arrays = np.zeros(12)
arrays[6]=1
arrays

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [8]:
np.arange(20,60)


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [9]:
arrays = np.arange(20)
arrays[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
np.arange(12,21).reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
np.random.random(8).reshape(2,2,2)

array([[[0.60558873, 0.3142867 ],
        [0.06591077, 0.51779276]],

       [[0.94987788, 0.80499975],
        [0.71144056, 0.47654085]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [13]:
arr = np.random.rand(81).reshape(9,9)
print(arr)
print('max:',arr.max())
print('min:',arr.min())

[[8.96696846e-04 5.04470357e-01 3.54069079e-01 9.50687163e-01
  2.51617832e-01 8.86014562e-01 3.54993467e-01 5.95618528e-01
  1.40870137e-01]
 [3.88788034e-01 5.16512583e-01 8.89965032e-04 8.53536642e-01
  3.48055329e-01 8.76187521e-01 1.16104380e-01 3.37698086e-01
  9.49293176e-01]
 [9.85705401e-01 4.79524947e-02 4.35158160e-01 2.82728890e-01
  2.06061244e-01 6.56389612e-01 5.79866663e-01 2.59018985e-01
  8.32900895e-01]
 [9.94027774e-01 1.46749811e-01 6.19874720e-01 8.71297284e-01
  3.34971387e-01 8.18165068e-01 4.13042468e-01 8.85291596e-01
  7.30058782e-01]
 [8.37664031e-01 4.25938760e-01 6.71393784e-01 3.74193216e-01
  1.97960575e-02 7.61719588e-01 7.38211832e-01 4.01733116e-02
  3.32215515e-01]
 [7.92419869e-01 1.01793296e-01 1.04024345e-01 6.00607307e-01
  5.59125313e-01 7.91568168e-01 9.05452092e-01 8.23614137e-01
  5.01260034e-01]
 [9.32371804e-01 5.44402074e-01 4.59829470e-01 6.23600501e-01
  1.39727866e-02 6.56291273e-01 6.69539452e-01 1.49705899e-01
  9.87417433e-01]
 [9.46

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
'''
NaN
False
False
NaN
True
False
'''

'\nNaN\nFalse\nFalse\nNaN\nTrue\nFalse\n'

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
arr1 = np.random.random(18).reshape(6,3)
arr2 = np.random.random(12).reshape(3,4)
print(arr1)
print()
print(arr2)
print()
arr1.dot(arr2)

[[0.79685421 0.11595529 0.8888392 ]
 [0.94922213 0.2515367  0.69337346]
 [0.43849156 0.06880066 0.34293387]
 [0.58690479 0.8126296  0.81641002]
 [0.47289044 0.82109178 0.50227614]
 [0.33714755 0.77347008 0.030791  ]]

[[0.84302378 0.67695949 0.43581472 0.16723383]
 [0.81798987 0.81775551 0.2094782  0.32072655]
 [0.26561195 0.75264576 0.64642783 0.55356173]]



array([[1.00270361, 1.30324216, 0.94614129, 0.66247829],
       [1.19013957, 1.37014505, 0.91459233, 0.62324156],
       [0.51702438, 0.61121086, 0.42719531, 0.28523188],
       [1.37634573, 1.67631065, 0.95376009, 0.81071557],
       [1.20371319, 1.36961601, 0.70277872, 0.62047006],
       [0.92509255, 0.88391937, 0.32886314, 0.32149958]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
'''
9
10
'''

'\n9\n10\n'

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [17]:
a = np.array([1,2])
b = np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
'''
RuntimeWarning: invalid value encountered in divide
RuntimeWarning: divide by zero encountered in floor_divide
RuntimeWarning: invalid value encountered in cast
'''

'\nRuntimeWarning: invalid value encountered in divide\nRuntimeWarning: divide by zero encountered in floor_divide\nRuntimeWarning: invalid value encountered in cast\n'

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [19]:
arr1 = np.array([1,2,4,7,3])
arr2 = np.array([3,9,1,0,2,4])
np.intersect1d(arr1,arr2)

array([1, 2, 3, 4])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [20]:
arr = np.random.uniform(low=0,high=10,size=10)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[7.95337752 3.62962802 5.5446739  5.72329777 7.25068906 0.33614942
 3.43387686 5.07830878 5.03587871 2.97477397]
[7. 3. 5. 5. 7. 0. 3. 5. 5. 2.]
[7. 3. 5. 5. 7. 0. 3. 5. 5. 2.]
[7 3 5 5 7 0 3 5 5 2]
[7. 3. 5. 5. 7. 0. 3. 5. 5. 2.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [21]:
np.repeat(np.arange(3),3).reshape(3,3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

arr 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [22]:
arr = np.random.rand(10)
print(arr)
print(np.sort(arr))

[0.12959109 0.20296946 0.38812325 0.97657622 0.14597602 0.98497902
 0.58479438 0.66522453 0.21579701 0.9990257 ]
[0.12959109 0.14597602 0.20296946 0.21579701 0.38812325 0.58479438
 0.66522453 0.97657622 0.98497902 0.9990257 ]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [23]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(np.allclose(arr1,arr2))
print(np.array_equal(arr1,arr2))

False
False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [24]:
arr1 = np.arange(18).reshape(6,3)
arr2 = np.arange(12).reshape(3,4)
np.dot(arr1,arr2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [25]:
arr = np.random.rand(5)
print(arr)
arr[arr.argmax()]=0
arr

[0.67141349 0.84769546 0.26845582 0.20101008 0.43691201]


array([0.67141349, 0.        , 0.26845582, 0.20101008, 0.43691201])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [26]:
today=np.datetime64('today')
yesterday=today-np.timedelta64(1,'D')
tomorrow=today+np.timedelta64(1,'D')
print(today)
print(yesterday)
print(tomorrow)

2025-07-23
2025-07-22
2025-07-24


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [27]:
dates = np.arange('2016-01-01','2016-02-01',dtype='datetime64[D]')
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [28]:
arr = np.random.uniform(low=-10,high=0,size=10)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[-6.09841205 -6.70984768 -5.40272345 -1.79620254 -1.43324846 -8.47126936
 -4.40083655 -7.1426275  -2.49275367 -9.60119723]
[ -7.  -7.  -6.  -2.  -2.  -9.  -5.  -8.  -3. -10.]
[ -7.  -7.  -6.  -2.  -2.  -9.  -5.  -8.  -3. -10.]
[-6 -6 -5 -1 -1 -8 -4 -7 -2 -9]
[-6. -6. -5. -1. -1. -8. -4. -7. -2. -9.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
result = np.add.reduce([a,b,c])
result

array([12, 15, 18])

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [30]:
arr = np.array([1,2,3,4,5])
result = np.zeros(len(arr) * 4 - 3, dtype=int)
result[::4] = arr
result

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [31]:
from numpy.lib.stride_tricks import as_strided
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

window_size = 4
n = len(a) - window_size + 1

stride = a.strides[0]

b = as_strided(a, shape=(n, window_size), strides=(stride, stride))

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [35]:
arr = np.random.randint(0, 10, size=20)
print("Massiv:", arr)

def find_most_frequent(arr):
    counts = np.bincount(arr)
    mode = np.argmax(counts)
    return mode, counts[mode]

mode_value, frequency = find_most_frequent(arr)
print(f"Eng ko‘p uchragan son: {mode_value}, {frequency} marta")

Massiv: [5 2 7 1 5 7 7 7 3 8 3 4 3 9 3 2 5 5 8 6]
Eng ko‘p uchragan son: 3, 4 marta


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

In [36]:
#NumPy kutubxonasida berilgan 2D massivdagi har bir ustunning o‘rtacha qiymatini qanday hisoblash mumkin?

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]
])

column_means = np.mean(a, axis=0)
print("Ustunlar bo‘yicha o‘rtachalar:", column_means)


Ustunlar bo‘yicha o‘rtachalar: [5. 6. 7. 8.]
